### ISSUE TITLE
lazydemo aborted when execute

### ISSUE THREAD

**Issue by gigglesun** [zhihaoy/dl-examples#1]
The lazydemo example aborted when execute.

Env:
OS: Linux
gcc version: 8.1.0
cmake vesion: 3.17

steps:
1. cmake ${src_dir} and make
2. ./lazydemo/lazydemo

output:
```bash
$ ./lazydemo/lazydemo 
address prior to use: 0x400950
implib-gen: ./liblazyrepromath.so: failed to load library: ./liblazyrepromath.so: cannot open shared object file: No such file or directory
lazydemo: liblazyrepromath.so.init.c:56: load_library: Assertion `0 && "Assertion in generated code"' failed.
Aborted (core dumped)
```

**Comment by zhihaoy** [comment]
As the error message suggests, it is looking for `./liblazyrepromath.so`, in other words, `liblazyrepromath.so` exactly under the current working directory. You will need to `cd` to the directory containing that file, and then run `lazydemo` using a relative path or a full path.
